const express = require('express');
const router = express.Router();

const authRoutes         = require('./auth.routes');
const userRoutes         = require('./user.routes');
const auditRoutes        = require('./audit.routes');
const notificationRoutes = require('./notification.routes');
const siteRoutes         = require('./site.routes');
const shiftRoutes        = require('./shift.routes');
const warehouseRoutes    = require('./warehouse.routes');
const machineRoutes              = require('./machine.routes');
const itemRoutes                 = require('./item.routes');
const productionParameterRoutes  = require('./productionParameter.routes');
const tagRoutes                  = require('./tag.routes');
const vendorRoutes               = require('./vendor.routes');
const vendorCostingRoutes        = require('./vendorCosting.routes');
const customFieldGroupRoutes     = require('./customFieldGroup.routes');
const integrationRoutes          = require('./integration.routes');
const stickerTemplateRoutes      = require('./stickerTemplate.routes');
const templateRoutes             = require('./template.routes');
const productionFormRoutes       = require('./productionForm.routes');
const uploadRoutes               = require('./upload.routes');
const bomRoutes                  = require('./bom.routes');
const cycleTimeRuleRoutes        = require('./cycleTimeRule.routes');
const downtimeReasonRoutes       = require('./downtimeReason.routes');
const packageRoutes              = require('./package.routes');
const ctqIssueRoutes             = require('./ctqIssue.routes');
const toolRoutes                 = require('./tool.routes');
const reportRoutes               = require('./report.routes');
const rfqRoutes                  = require('./rfq.routes');
const quotationRoutes            = require('./quotation.routes');
const customerOrderRoutes        = require('./customerOrder.routes');
const grnRoutes                  = require('./grn.routes');
const inventoryRoutes            = require('./inventory.routes');
const materialRequestRoutes      = require('./materialRequest.routes');
const issueSlipRoutes            = require('./issueSlip.routes');
const stockAdjustmentRoutes      = require('./stockAdjustment.routes');
const workOrderRoutes            = require('./workOrder.routes');
const jobCardRoutes              = require('./jobCard.routes');
const iqcInspectionRoutes        = require('./iqcInspection.routes');
const lqcInspectionRoutes        = require('./lqcInspection.routes');
const pqcInspectionRoutes        = require('./pqcInspection.routes');
const oqcInspectionRoutes        = require('./oqcInspection.routes');
const productionScheduleRoutes   = require('./productionSchedule.routes');
const scrapVoucherRoutes         = require('./scrapVoucher.routes');
const purchaseOrderRoutes        = require('./purchaseOrder.routes');
const scarRoutes                 = require('./scar.routes');
const subcontractChallanRoutes   = require('./subcontractChallan.routes');
const trainingTopicRoutes         = require('./trainingTopic.routes');
const roleRequirementRoutes       = require('./roleRequirement.routes');
const trainingRecordRoutes        = require('./trainingRecord.routes');
const trainingEffectivenessRoutes = require('./trainingEffectiveness.routes');
const transporterRoutes           = require('./transporter.routes');
const dispatchOrderRoutes         = require('./dispatchOrder.routes');
const deliveryChallanRoutes       = require('./deliveryChallan.routes');
// Sprint 4
const capaRoutes                  = require('./capa.routes');
const ncrRoutes                   = require('./ncr.routes');
const complaintRoutes             = require('./complaint.routes');
const drawingRoutes               = require('./drawing.routes');
const checkSheetRoutes            = require('./checkSheet.routes');
const pfmeaRoutes                 = require('./pfmea.routes');

// Mount routes
router.use('/auth',          authRoutes);
router.use('/users',         userRoutes);
router.use('/audit',         auditRoutes);
router.use('/notifications', notificationRoutes);
router.use('/sites',         siteRoutes);
router.use('/shifts',        shiftRoutes);
router.use('/warehouses',    warehouseRoutes);
router.use('/machines',              machineRoutes);
router.use('/items',                 itemRoutes);
router.use('/production-parameters', productionParameterRoutes);
router.use('/tags',                  tagRoutes);
router.use('/vendors',               vendorRoutes);
router.use('/vendor-costings',       vendorCostingRoutes);
router.use('/custom-field-groups',   customFieldGroupRoutes);
router.use('/integrations',          integrationRoutes);
router.use('/sticker-templates',     stickerTemplateRoutes);
router.use('/templates',             templateRoutes);
router.use('/production-forms',      productionFormRoutes);
router.use('/upload',                uploadRoutes);
router.use('/boms',                  bomRoutes);
router.use('/cycle-time-rules',      cycleTimeRuleRoutes);
router.use('/downtime-reasons',      downtimeReasonRoutes);
router.use('/packages',              packageRoutes);
router.use('/ctq-issues',            ctqIssueRoutes);
router.use('/tools',                 toolRoutes);
router.use('/reports',               reportRoutes);
router.use('/rfqs',                  rfqRoutes);
router.use('/quotations',            quotationRoutes);
router.use('/customer-orders',       customerOrderRoutes);
router.use('/grns',                  grnRoutes);
router.use('/inventory',             inventoryRoutes);
router.use('/material-requests',     materialRequestRoutes);
router.use('/issue-slips',           issueSlipRoutes);
router.use('/stock-adjustments',     stockAdjustmentRoutes);
router.use('/work-orders',           workOrderRoutes);
router.use('/job-cards',             jobCardRoutes);
router.use('/iqc-inspections',       iqcInspectionRoutes);
router.use('/lqc-inspections',       lqcInspectionRoutes);
router.use('/pqc-inspections',       pqcInspectionRoutes);
router.use('/oqc-inspections',       oqcInspectionRoutes);
router.use('/production-schedules',  productionScheduleRoutes);
router.use('/scrap-vouchers',        scrapVoucherRoutes);
router.use('/purchase-orders',       purchaseOrderRoutes);
router.use('/scars',                 scarRoutes);
router.use('/subcontract-challans',  subcontractChallanRoutes);
router.use('/hr/training-topics',         trainingTopicRoutes);
router.use('/hr/role-requirements',       roleRequirementRoutes);
router.use('/hr/training-records',        trainingRecordRoutes);
router.use('/hr/training-effectiveness',  trainingEffectivenessRoutes);
router.use('/dispatch/transporters',      transporterRoutes);
router.use('/dispatch/orders',            dispatchOrderRoutes);
router.use('/dispatch/challans',          deliveryChallanRoutes);
// Sprint 4: Quality
router.use('/quality/capa',              capaRoutes);
router.use('/quality/ncr',               ncrRoutes);
router.use('/quality/complaints',        complaintRoutes);
// Sprint 4: NPD
router.use('/npd/drawings',              drawingRoutes);
router.use('/npd/check-sheets',          checkSheetRoutes);
router.use('/npd/pfmea',                 pfmeaRoutes);

module.exports = router;
