const router = require('express').Router();
const { authenticate } = require('../config/middleware');
const ctrl = require('../modules/procurement/controller/purchaseOrder.controller');
router.get('/',              authenticate, ctrl.getAll);
router.get('/:id',           authenticate, ctrl.getById);
router.post('/',             authenticate, ctrl.create);
router.patch('/:id',         authenticate, ctrl.update);
router.patch('/:id/send',    authenticate, ctrl.send);
router.patch('/:id/receive', authenticate, ctrl.receive);
router.delete('/:id',        authenticate, ctrl.delete);
module.exports = router;
