const router = require('express').Router();
const { authenticate } = require('../config/middleware');
const ctrl = require('../modules/production/controller/scrapVoucher.controller');
router.get('/',                 authenticate, ctrl.getAll);
router.get('/:id',              authenticate, ctrl.getById);
router.post('/',                authenticate, ctrl.create);
router.patch('/:id',            authenticate, ctrl.update);
router.patch('/:id/authorize',  authenticate, ctrl.authorize);
router.patch('/:id/reject',     authenticate, ctrl.reject);
router.delete('/:id',           authenticate, ctrl.delete);
module.exports = router;
